### ISSUE TITLE
Explore adding Kubernetes Templates to GitOps sidebar

### ISSUE THREAD

**Issue by RandomFractals** [weaveworks/vscode-gitops-tools#11]
k8s tools already have some built-in: https://github.com/Azure/vscode-kubernetes-tools/tree/master/snippets

We can present them in a custom k8s snippets view similar to this generic snippets extension: https://github.com/RandomFractals/vscode-snippets-viewer

and add GitOps/Flux specific snippets in `/snippets` as needed.

**Comment by RandomFractals** [comment]
This k8s templates vscode extension actually has those code snippets configured in standard vscode `.json` snippet file format: 

https://marketplace.visualstudio.com/items?itemName=lunuan.kubernetes-templates

snippets code: https://github.com/lunuan/vscode-kubernetes-templates/tree/master/snippets

you can preview them in snippets viewer:

![k8s-templates](https://user-images.githubusercontent.com/656833/130355638-de83f113-39d2-4468-9a54-9a4ccd36b69b.png)

we can add your k8s templates similarly to this GitOps extension for quick k8s code templates preview and use in `.yml` configs.

**Comment by kingdonb** [comment]
There is an integration with GitopsTemplate, but it's difficult to demo in public because the GitopsTemplate CRD is not published freely. However, if you are using Weave GitOps Enterprise, there is a possibility to stamp out resources by template even today. You can do it locally for pull-requests, very much like the experience with a pull request in WGE UI.

I don't think this is exactly what you had in mind, I'm just going through cleaning up old issues that are unlikely to get closed productively. But we also do have something a bit like this now.
