### ISSUE TITLE
Leo: Investigate any requirements for publishing

### ISSUE THREAD

**Issue by josefaworks** [weaveworks/vscode-gitops-tools#168]

**Comment by RandomFractals** [comment]
@josefaworks that process is described here: https://code.visualstudio.com/api/working-with-extensions/publishing-extension

WeaveWorks would need to create Azure DevOps account in order to publish this extension in VS marketplace:

https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/create-organization?view=azure-devops

@usernamehw is familiar with that process and can walk you through it.
