### ISSUE TITLE
Create a Bug/Feature Template

### ISSUE THREAD

**Issue by jonathan-innis** [weaveworks/vscode-gitops-tools#178]
Repos that are open to external contributors generally have a bug and feature template to make it easier to file and categorize features and bugs

**Comment by murillodigital** [comment]
@usernamehw Guessing there have to be some templates already available and in use by other public extensions that we can leverage. Please advise on best practices from other extensions and add templates to the repo. (https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms)

**Comment by usernamehw** [comment]
Used Python extension as an example.

Feature request template is simple comment in markdown:

```
<!-- Describe the feature you'd like. -->
```

For bug report - a form template with 4 textareas: 
- `Expected behaviour`
- `Actual behaviour`
- `Steps to reproduce`
- `Versions`

New command to quickly fill the `Versions` part of the bug report:

`gitops.showInstalledVersions` **GitOps: Show Installed Versions**

<img width="500" src="https://user-images.githubusercontent.com/9638156/147926290-5bcf8d93-234a-49ec-8b69-e1c8bcaf1a4f.png">
