### ISSUE TITLE
Allow for the creation of arbitrary GitRepository Sources

### ISSUE THREAD

**Issue by murillodigital** [weaveworks/vscode-gitops-tools#188]
Currently, the only way to add a new GitRepository is by having the repo open as a folder in VS Code.

This issue should cover the following two changes:

1) If a Git repository is currently open in VS Code, ask the user if the source to add should be the one currently open in VS code, if the answer is yes, continue as currently implemented.

2) If there is no Git repo open OR the user answers NO the the question above, display a dialog for the user to enter all necessary parameters.

**Comment by usernamehw** [comment]
This issue is related to #186.

It works without the confirmation now: when there is a git repository opened in VSCode - the extension prefills the inputs `Name`, `Url` & `Branch`. When no folder is opened - those inputs are empty.

![create_source](https://user-images.githubusercontent.com/9638156/147946757-ae335d26-5318-456b-94fc-6c5045d64788.gif)

@murillodigital let me know if you still want the confirmation popup.
