### ISSUE TITLE
Live synchronization

### ISSUE THREAD

**Issue by juozasg** [weaveworks/vscode-gitops-tools#255]
Seeing flux cluster changes without having to click Refresh would make the extension more useful for interactive work and cluster observation.

**Comment by kingdonb** [comment]
The priority is high because it feels like a critical feature. The risk is that it's not implementable without major overhaul.

If we can determine the level of work required to make streaming updates a reality, it can be gated behind a feature opt-in so we mitigate the risk of severe performance impact. I am concerned that implementing this feature will result in a noticeable difference in the amount of load this extension places on the cluster, or on the user's workstation/network or what have you.

**Comment by kingdonb** [comment]
This was delivered in the 0.25.0 release! It's still on the table for performance improvements, we're doing prereleases with fixes as we get the ideas, it isn't perfect yet, but you don't have to click the refresh to see updates in 99% of cases now. 🎉
